### ISSUE TITLE
Auth verification error not handled as expected

### ISSUE THREAD

**Issue by atej** [nowaythatworked/auth-astro#58]
Setup with an Email provider. Sign in via magic link works.

The problem arises when you click on a magic link that was previously used. Expected behaviour is redirection to the [error page](https://authjs.dev/guides/basics/pages#error-page) with the search param `?error=Verification`.

However, it leads to a `TypeError immutable`

The [erring line](https://github.com/nowaythatworked/auth-astro/blob/d3f9aceec7bb3c28693589ebe0ad449e476415a2/server.ts#L58) 

`res.headers.delete('Set-Cookie')`

This, I suspect is because the headers `guard` is set to `immutable`. More [here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Basic_concepts#guard)

So, a work-around:

```js
// ...
try {
  res.headers.delete('Set-Cookie')
} catch(error) {
  if (error instanceof TypeError) {
    const mutableHeaders = new Headers(res.headers)
    mutableHeaders.delete('Set-Cookie')
    return new Response(res.body, {
      headers: res.headers
    })
  }
}
// ...
```

This avoids the crash, but still no redirection to the error page, simply a `200` response.

I do see the error being logged though:

```shell
[auth][error] Verification: Read more at https://errors.authjs.dev#verification
    at Module.callback (file:///Users/aseem/Sites/astro-xata-vercel/node_modules/@auth/core/lib/actions/callback/index.js:126:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthInternal (file:///Users/aseem/Sites/astro-xata-vercel/node_modules/@auth/core/lib/index.js:27:24)
    at async Module.Auth (file:///Users/aseem/Sites/astro-xata-vercel/node_modules/@auth/core/index.js:104:29)
    at async eval (/Users/aseem/Sites/astro-xata-vercel/node_modules/auth-astro/server.ts:25:17)
    at async Module.GET (/Users/aseem/Sites/astro-xata-vercel/node_modules/auth-astro/server.ts:55:14)
    at async renderEndpoint (file:///Users/aseem/Sites/astro-xata-vercel/node_modules/astro/dist/runtime/server/endpoint.js:25:20)
    at async file:///Users/aseem/Sites/astro-xata-vercel/node_modules/astro/dist/core/endpoint/index.js:121:14
    at async callMiddleware (file:///Users/aseem/Sites/astro-xata-vercel/node_modules/astro/dist/core/middleware/callMiddleware.js:12:10)
    at async callEndpoint (file:///Users/aseem/Sites/astro-xata-vercel/node_modules/astro/dist/core/endpoint/index.js:120:16)
13:28:47 [200] /api/auth/callback/resend 1008ms
```

**Comment by atej** [comment]
This is my current patch:

```js
// ...
try {
  res.headers.delete('Set-Cookie')
} catch(error) {
  if (error instanceof TypeError) {
    return redirect(prefix + '/error?error=Verification', 302)
  }
  return redirect(prefix + '/error?error=Default', 302)
}
//...
```

**Comment by kcoderhtml** [comment]
I just encountered this issue as well with the slack integration

**Comment by kcoderhtml** [comment]
I was able to fix this issue by adding `checks: ["pkce", "nonce"]` to the slack config in the auth.config.mjs file
