### ISSUE TITLE
Discord provider is missing user.id in the session object

### ISSUE THREAD

**Issue by LFDPhoenix1411** [nowaythatworked/auth-astro#62]
If I log the session, I only get this JSON Object back and the `user.id` is missing for some reason

Session Object :
```js
{
  user: {
    name: 'staku',
    email: 'name@example.com',
    image: 'https://cdn.discordapp.com/avatars/444560731300429844/28ef1f92c9bc92f919fa2ea5182ecb16.png'
  },
  expires: '2024-03-11T01:46:51.264Z'
}
```

auth.config.ts : 
```ts
import Discord from '@auth/core/providers/discord';

import { defineConfig } from 'auth-astro';

export default defineConfig({
	providers: [
		Discord({
			clientId: import.meta.env.DISCORD_CLIENT_ID,
			clientSecret: import.meta.env.DISCORD_CLIENT_SECRET,
		}),
	],
});

```

**Comment by julianfbeck** [comment]
I have the same error using github. Did you find a solution?

**Comment by julianfbeck** [comment]
The soluzion is adding a callback inside the auth properties, thats add the userid
```
  ],
   callbacks: {
    session({ session, user }) {
      if (session.user) {
        session.user.id = user.id;
      }
      return session;
    }
  }
```

**Comment by LFDPhoenix1411** [comment]
> The soluzion is adding a callback inside the auth properties, thats add the userid
> 
> ```
>   ],
>    callbacks: {
>     session({ session, user }) {
>       if (session.user) {
>         session.user.id = user.id;
>       }
>       return session;
>     }
>   }
> ```


```console
[auth][error] JWTSessionError: Read more at https://errors.authjs.dev#jwtsessionerror
[auth][cause]: TypeError: Cannot read properties of undefined (reading 'id')
    at Object.session (eval at instantiateModule (file:///C:/.../auth/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54755:28), <anonymous>:18:31)
    at Module.session (file:///C:/.../auth/node_modules/@auth/core/lib/actions/session.js:35:52)
    at async AuthInternal (file:///C:/.../auth/node_modules/@auth/core/lib/index.js:35:24)
    at async Module.Auth (file:///C:/.../auth/node_modules/@auth/core/index.js:104:29)
    at async Module.getSession (eval at instantiateModule (file:///C:/.../auth/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54755:28), <anonymous>:56:20)
    at async eval (eval at instantiateModule (file:///C:/.../auth/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54755:28), <anonymous>:16:19)
    at async AstroComponentInstance.render (eval at instantiateModule (file:///C:/.../auth/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54755:28), <anonymous>:44:7)    
    at async Object.render (eval at instantiateModule (file:///C:/.../auth/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54755:28), <anonymous>:356:7)
    at async Module.renderChild (eval at instantiateModule (file:///C:/.../auth/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54755:28), <anonymous>:36:5)
[auth][details]: {}
``` 

Doesn't work for me, I just get an error message when I try to log in, where should I add this?
Adding to `auth.config.ts` did not work.

**Comment by julianfbeck** [comment]
For me i added it likethis tothe auth config, but i only tested it for github, not for discord
```
import GitHub from '@auth/core/providers/github';
import { DrizzleAdapter } from '@auth/drizzle-adapter';

import { db } from './src/utils/db';

import type { AuthConfig } from '@auth/core';
import { env } from '@/t3-env';

export default {
  adapter: DrizzleAdapter(db),
  providers: [
    GitHub({
      clientId: env.GITHUB_CLIENT_ID,
      clientSecret: env.GITHUB_CLIENT_SECRET
    })
  ],
  callbacks: {
    session({ session, user }) {
      if (session.user) 
        session.user.id = user.id;
      }
      return session;
    }
  }
} satisfies AuthConfig;
```

**Comment by Cocodrulo** [comment]
Plss solve this

**Comment by willnode** [comment]
I use this to get user ID

```
export default defineConfig({
  providers: [
    Credentials({
         ...
    }),
  ],
  callbacks: {
    session({ session, token }) {
      if (session.user && token?.sub) {
        session.user.id = token.sub;
      }
      return session;
    }
  }
})
```

**Comment by Cocodrulo** [comment]
But that does not retrieve the actual discord ID does it? it returns a unique identificatory number but not the actual discord ID right?

**Comment by Cocodrulo** [comment]
But that does not retrieve the actual discord ID does it? it returns a unique identificator but

**Comment by willnode** [comment]
I think it is.

https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/discord.ts#L164-L168

After reading this repo code, I came to know that 'id' is forwarded as 'token.sub'

**Comment by Cocodrulo** [comment]
No for I can see. ID is now smth that not looks like the discord ID

![image](https://github.com/nowaythatworked/auth-astro/assets/142546774/28096779-e6eb-4b0a-b3fe-50089b3ee2fc)

**Comment by fearandesire** [comment]
For those struggling - the solution I used was a small function to extract it from the `image` URL.
The numbers after `/avatars` has the User ID, its standard with Discord.

```
/**
 * @summary Extracts the Discord User ID from the `image` field
 * Custom utility function designed to enable us to get a User ID from a session (using auth-astro)
 * @param {string} imageUrl
 * @returns {string}
 */
export function extractUserIdFromImage(imageUrl: string): string {
  const match = imageUrl.match(/avatars\/(\d+)\//);
  return match ? match[1] : '';
}

```

**Comment by Cocodrulo** [comment]
And what if it has no avatar, then the image url is: 'https://cdn.discordapp.com/embed/avatars/0.png'

**Comment by fearandesire** [comment]
>  And what if it has no avatar, then the image url is: 'https://cdn.discordapp.com/embed/avatars/0.png' @fearandesire 

Great point! I haven't come across this issue yet myself. That said, I just offered a solution that works for my needs. I'm not sure what to do in the event they don't have an avatar.

**Comment by fearandesire** [comment]
Following up, the solution provided by @willnode works! I explored this option for a site I recently launched, and the solution I provided prior was the cause of a silly bug as some users did not have avatars.

To clarify, for me -- [this solution](https://github.com/nowaythatworked/auth-astro/issues/62#issuecomment-2198130310) returns the User ID. I don't seem to get any UUID-like string as @Cocodrulo got [here](https://github.com/nowaythatworked/auth-astro/issues/62#issuecomment-2198506831)

**Comment by lioncommunity-es** [comment]
I dont know why, sometimes token.sub gives the discord ID but other times it return thar strange UUID-like string. I was finally getting the discord ID and then suddenly token.sub was that kind of string again. I don't really understand.

**Comment by Cocodrulo** [comment]
I dont know why, sometimes token.sub gives the discord ID but other times it return thar strange UUID-like string. I was finally getting the discord ID and then suddenly token.sub was that kind of string again. I don't really understand.

**Comment by JusticeMatthew** [comment]
Any update on a fix for this issue or alternative work arounds?

I get the same issues above when using the callbacks, either `user.id` is not found or the `token.sub` is the weird UUID like value

Would love to continue using the library but I need that ID, there's really no point without it

**Comment by NicoToff** [comment]
> For those struggling - the solution I used was a small function to extract it from the `image` URL.
> The numbers after `/avatars` has the User ID, its standard with Discord.
> 
> ```
> /**
>  * @summary Extracts the Discord User ID from the `image` field
>  * Custom utility function designed to enable us to get a User ID from a session (using auth-astro)
>  * @param {string} imageUrl
>  * @returns {string}
>  */
> export function extractUserIdFromImage(imageUrl: string): string {
>   const match = imageUrl.match(/avatars\/(\d+)\//);
>   return match ? match[1] : '';
> }
> 
> ```

I love this 😂 Very clever, I'm just concerned it will break if Discord randomly changes their avatar naming pattern.

**Comment by FurStaku** [comment]
> For those struggling - the solution I used was a small function to extract it from the `image` URL. The numbers after `/avatars` has the User ID, its standard with Discord.
> 
> ```
> /**
>  * @summary Extracts the Discord User ID from the `image` field
>  * Custom utility function designed to enable us to get a User ID from a session (using auth-astro)
>  * @param {string} imageUrl
>  * @returns {string}
>  */
> export function extractUserIdFromImage(imageUrl: string): string {
>   const match = imageUrl.match(/avatars\/(\d+)\//);
>   return match ? match[1] : '';
> }
> ```

problem here is that not everyone has a profile picture, so if you don't have one, it won't work because the avatar string is empty

**Comment by JusticeMatthew** [comment]
All right here is my hacky solution because I don't need access to the users email

```ts
import Discord from '@auth/core/providers/discord';
import { defineConfig } from 'auth-astro';

export default defineConfig({
  providers: [
    Discord({
      clientId: import.meta.env.DISCORD_CLIENT_ID,
      clientSecret: import.meta.env.DISCORD_CLIENT_SECRET,
      async profile(profile) {
        return {
          name: profile.username,
          email: profile.id,
          image: `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.png`,
        };
      },
    }),
  ],
});
```

**Comment by Cocodrulo** [comment]
> All right here is my hacky solution because I don't need access to the users email
> 
> ```ts
> import Discord from '@auth/core/providers/discord';
> import { defineConfig } from 'auth-astro';
> 
> export default defineConfig({
>   providers: [
>     Discord({
>       clientId: import.meta.env.DISCORD_CLIENT_ID,
>       clientSecret: import.meta.env.DISCORD_CLIENT_SECRET,
>       async profile(profile) {
>         return {
>           name: profile.username,
>           email: profile.id,
>           image: `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.png`,
>         };
>       },
>     }),
>   ],
> });
> ```
> 
> gives me this from the `session` (verified that is my correct ID)
> 
> ```js
> {
>   user: {
>     name: 'arknoodle',
>     email: '223864942615461888',
>     image: 'https://cdn.discordapp.com/avatars/223864942615461888/656ffa166759d7f24a73295a68ba023e.png'
>   },
>   expires: '2024-09-10T23:21:08.634Z'        
> }
> ```

Which version are u suing?

**Comment by vextrogen** [comment]
Hey, this is still happening.
@Cocodrulo 's solution works for me but it's super hacky. Would appreciate a fix from a contributor on this.

**Comment by vextrogen** [comment]
I did actually find a callback function that worked for me.

Following https://next-auth.js.org/configuration/callbacks#sign-in-callback there is a bunch more data we can access. I was able to get the discord user id from the `profile.id`

It seems that "user" contains the very basic profile data, "account" contains data about the OAuth Application used to make the connection, "profile" is where all our interesting Discord logged in user data exists, and "email" and "credentials" I didn't check or are null.

**Comment by Cocodrulo** [comment]
But profile only exists on signing in not in session, that's the problem for me

**Comment by vextrogen** [comment]
Yep. I just noted that. It's also a problem for me, so we are back to square 1 x)

**Comment by JusticeMatthew** [comment]
> > All right here is my hacky solution because I don't need access to the users email
> > import Discord from '@auth/core/providers/discord';
> > import { defineConfig } from 'auth-astro';
> > 
> > export default defineConfig({
> >   providers: [
> >     Discord({
> >       clientId: import.meta.env.DISCORD_CLIENT_ID,
> >       clientSecret: import.meta.env.DISCORD_CLIENT_SECRET,
> >       async profile(profile) {
> >         return {
> >           name: profile.username,
> >           email: profile.id,
> >           image: `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.png`,
> >         };
> >       },
> >     }),
> >   ],
> > });
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gives me this from the `session` (verified that is my correct ID)
> > {
> >   user: {
> >     name: 'arknoodle',
> >     email: '223864942615461888',
> >     image: 'https://cdn.discordapp.com/avatars/223864942615461888/656ffa166759d7f24a73295a68ba023e.png'
> >   },
> >   expires: '2024-09-10T23:21:08.634Z'        
> > }
> 
> Which version are u using?

4.2.0

Fwiw I think this particular issue with the user ID is a problem with the discord API, as I've since switched to Better Auth and had to implement the same sort of thing

**Comment by vextrogen** [comment]
Did this ever get fixed or looked into at all?

**Comment by julianfbeck** [comment]
@vextrogen i just moved to better-auth 😅

**Comment by nowaythatworked** [comment]
Yep, better-auth is the way to go. This project was never intended to live this long and will be archived soon.
Better-auth is the better way to go and they already have an Astro adapter

**Comment by vextrogen** [comment]
Bleak. Well I've got a workaround but good to know for the next project. Thanks all. Suggest this issue gets closed with a WONTFIX so others know.
