### ISSUE TITLE
Errors trying to use Keycloak as OIDC provider

### ISSUE THREAD

**Issue by benmarte** [nowaythatworked/auth-astro#73]
I'm evaluating Astro for a project, I'm using Keycloak as my OIDC provider and I'm running into an issue when trying to login.

This is the contents of my `auth.config.mjs`:

```
import Keycloak from '@auth/core/providers/keycloak';
import { defineConfig } from 'auth-astro';

export default defineConfig({
  providers: [
    Keycloak({
      clientId: import.meta.env.AUTH_KEYCLOAK_ID,
      clientSecret: import.meta.env.AUTH_KEYCLOAK_SECRET,
      issuer: `${import.meta.env.KEYCLOAK_URL}/realms/agmd-frontend`,
			authorization: { params: { scope: "profile email openid" } },
			async profile(profile) {
				return {
					id: profile.sub,
					name: profile.name,
					firstname: profile.given_name,
					lastname: profile.family_name,
					email: profile.email,
				};
			},
    }),
  ],
});
```

This is the error I get when trying to login:

```
agmd-frontend-1           | [auth][error] TypeError: fetch failed
agmd-frontend-1           |     at node:internal/deps/undici/undici:12502:13
agmd-frontend-1           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
agmd-frontend-1           |     at async getAuthorizationUrl (file:///app/node_modules/@auth/core/lib/actions/signin/authorization-url.js:18:35)
agmd-frontend-1           |     at async Module.signIn (file:///app/node_modules/@auth/core/lib/actions/signin/index.js:10:56)
agmd-frontend-1           |     at async AuthInternal (file:///app/node_modules/@auth/core/lib/index.js:58:24)
agmd-frontend-1           |     at async Module.Auth (file:///app/node_modules/@auth/core/index.js:104:29)
agmd-frontend-1           |     at async eval (/app/node_modules/auth-astro/server.ts:25:17)
agmd-frontend-1           |     at async Module.POST (/app/node_modules/auth-astro/server.ts:47:14)
agmd-frontend-1           |     at async renderEndpoint (file:///usr/local/lib/node_modules/astro/dist/runtime/server/endpoint.js:34:20)
agmd-frontend-1           |     at async callMiddleware (file:///usr/local/lib/node_modules/astro/dist/core/middleware/callMiddleware.js:21:10)
agmd-frontend-1           | 23:13:35 [200] POST /api/auth/signin/keycloak 4ms
agmd-frontend-1           | 23:13:35 [500] /api/auth/error 4ms
```

My issuer URL is resolving just fine so I'm not sure what URL authjs is trying to fetch.

Any ideas on how I can fix or debug this? There's not that much information on how to use keycloak as a provider with astro and authjs.

Thanks.

**Comment by ValentinoChiappanni** [comment]
Hello, were you able to fix it?
I also want to use keycloak, if you could fix it, can you give me an example?

**Comment by benmarte** [comment]
Hi @ValentinoChiappanni I ended up not using astro but I did make a repo with it set up so you can see how I got it working.

Hope this helps: https://github.com/benmarte/astro-keycloak-example

**Comment by ValentinoChiappanni** [comment]
thank you so much
