### ISSUE TITLE
Error after upgrading Astro to beta12

### ISSUE THREAD

**Issue by dos41gw** [nowaythatworked/auth-astro#88]
Auth-astro was doing fine with astro 5 at least up to version 5.0.0-beta-10. After update to 5.0.0-beta-12 appeared error:

```
Vite module runner has been closed.
  Location:
    /node_modules/vite/dist/node/module-runner.js:1196:13
  Stack trace:
    at SSRCompatModuleRunner.getModuleInformation (/node_modules/vite/dist/node/module-runner.js:1196:13)
    at request (/node_modules/vite/dist/node/module-runner.js:1222:99)
    at astro:config:setup (/home/chmo/tremendous-trappist/node_modules/auth-astro/src/integration.ts:27:41)
    at async createContainer (/node_modules/astro/dist/core/dev/container.js:25:14)
    at async dev (/node_modules/astro/dist/core/dev/dev.js:23:19)
```

**Steps to Reproduce:**

```
npm create astro@latest -- --ref next
npx @astrojs/upgrade beta
Add auth-astro and provide basic config
npm run dev
```

**Expected Behavior:**

Should work fine. 

**Environment:**

Operating System: ubuntu serever 22.04
astro@5.0.0-beta.12
auth-astro@4.1.3
@auth/core@0.37.4

**Additional Notes:**

I suppose it's related to vite bumped to v6.0.0 in beta12. 
https://github.com/withastro/astro/releases/tag/astro%405.0.0-beta.12
in integration.ts commenting `const { dirname, join } = await import('node:path')` and adding ` import { dirname, join }  from 'node:path' ` some kind fixes problem.

**Comment by TheOtterlord** [comment]
This is fixed in the latest version `4.2.0`
